---
- name: Deploy Dev environment on Azure
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Create VMs
      local_action:
      module: azure_rm_virtualmachine
      resource_group: AnsibleResourceGroup
      name: myVM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.3'
        version: latest
