---
- name: Deploy Dev environment on AWS
  hosts: localhost
  connection: local
  gather_facts: false

 # include vars file
  vars_files:
    - group_vars/ec2dev_aws_vars.yml

  tasks:
    - name: Create EC2 Instance(s)
      ec2:
        access_key: "{{ ec2_access_key }}"
        secret_key: "{{ ec2_secret_key }}"
        region: "{{ ec2_region }}"
        group: "{{ ec2_security_group }}"
        keypair: "{{ ec2_keypair }}"
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ item.ami_id }}"
        vpc_subnet_id: "{{ ec2_subnet_id  }}"
        assign_public_ip: yes
        wait: True
        wait_timeout: 600
        instance_tags:
          Name: "{{ customer }}-{{ vpc_name }}-{{ item.name }}-01"
          Environment: "{{ ec2_environment }}"
          Server_Role: "{{ item.role }}"
        count: "{{ ec2_instance_count }}"
      with_items: "{{ instances }}"
      register: ec2
