---
- name: Deploy Dev environment on AWS
  hosts: localhost
  connection: local
  gather_facts: false

 # include vars file
  vars_files:
    - group_vars/ec2staging_aws_vars.yml

  tasks:
    - name: Create security group for instances
      ec2_group:
        name: "{{ ec2_environment }}-sec-group"
        description: "New security for {{ ec2_environment }} Instances"
        region: "{{ ec2_region }}"
        vpc_id: "{{ ec2_vpc_id }}"
        rules:
          - proto: "tcp"
            from_port: 22
            to_port: 22
            cidr_ip: "0.0.0.0/0"
        rules_egress:
          - proto: "all"
            cidr_ip: "0.0.0.0/0"
      register: secgrp

    - name: Create EC2 Instance(s)
      ec2:
        region: "{{ ec2_region }}"
        group_id: "{{ secgrp.group_id }}"
        keypair: "{{ ec2_keypair }}"
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ item.ami_id }}"
        vpc_subnet_id: "{{ ec2_subnet_id  }}"
        assign_public_ip: yes
        wait: True
        wait_timeout: 600
        instance_tags:
          Name: "{{ customer }}-{{ vpc_name }}-{{ item.name }}-01"
          Environment: "{{ ec2_environment }}"
          Server_Role: "{{ item.role }}"
        count: "{{ ec2_instance_count }}"
      with_items: "{{ instances }}"
      register: ec2
