---
- name: Deploy Dev Test environment on VMware
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    vmw_environment: prd
    vmw_network: "POC-ETI-DEV"

  roles:
    - role: nehrman.vmw
      instance_name: db
      instance_role: "db"
      instance_ansible_port: "22"
      instance_ansible_user: "ansible"
      os_type: "linux"
      vmw_os_type: "debian8_64Guest"
      vmw_template: "00.Templates/TEMPLATE_LINUXDEBIAN8.7"

    - role: nehrman.vmw
      instance_name: web
      instance_role: "web"
      instance_ansible_port: "22"
      instance_ansible_user: "ansible"
      os_type: "linux"
      vmw_template: "00.Templates/TEMPLATE_LINUXDEBIAN8.7"

    - role: nehrman.vmw
      instance_name: client
      instance_role: "client"
      instance_ansible_port: "5986"
      instance_ansible_user: "ansible"
      instance_win_initial_password: "P@ssw0rd01"
      os_type: "windows"
      vmw_os_type: "windows8Server64Guest"
      vmw_template: "00.Templates/TEMPLATE_2012r2-DC-blank"
