---
- name: Deploy Staging environment on VMware
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    vmw_environment: dev

  roles:
    - role: nehrman.vmw
      instance_name: db
      instance_role: "db"
      instance_ansible_port: "22"
      instance_ansible_user: "ansible"
      os_type: "linux"
      vmw_templates:

    - role: nehrman.vmw
      instance_name: web
      instance_role: "web"
      instance_ansible_port: "22"
      instance_ansible_user: "ansible"
      os_type: "linux"
      vmw_templates:

    - role: nehrman.vmw
      instance_name: client
      instance_role: "client"
      instance_ansible_port: "5986"
      instance_ansible_user: "ansible"
      instance_win_initial_password: "P@ssw0rd01"
      os_type: "windows"
      vmw_templates:
